CREATE DATABASE IF NOT EXISTS image_restore;
USE image_restore;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'user',
  force_password_change TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'user';
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS force_password_change TINYINT(1) NOT NULL DEFAULT 0;
UPDATE users
SET role = 'user'
WHERE role IS NULL OR role = '';

CREATE TABLE IF NOT EXISTS user_sessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  token TEXT NOT NULL,
  is_revoked TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  caption TEXT NULL,
  icon_path TEXT NULL,
  original_path TEXT NOT NULL,
  current_path TEXT NOT NULL,
  is_shared TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE images
  ADD COLUMN IF NOT EXISTS is_shared TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE images
  ADD COLUMN IF NOT EXISTS caption TEXT NULL;
ALTER TABLE images
  ADD COLUMN IF NOT EXISTS icon_path TEXT NULL;

CREATE TABLE IF NOT EXISTS image_versions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  image_id INT NOT NULL,
  version_num INT NOT NULL,
  file_path TEXT NOT NULL,
  is_shared TINYINT(1) NOT NULL DEFAULT 0,
  operations_json JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_image_version (image_id, version_num),
  FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE
);

ALTER TABLE image_versions
  ADD COLUMN IF NOT EXISTS is_shared TINYINT(1) NOT NULL DEFAULT 0;
